name: xeramiya.net Redeployer
on: [push]
jobs:
  vercel-redeploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_DEPLOY_HOOK_URL: ${{secrets.VERCEL_DEPLOY_HOOK_URL}}
    steps:
      - run: curl -X POST $VERCEL_DEPLOY_HOOK_URL